// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Metadata.Enums;
using System;
using System.Collections.Generic;

#nullable disable

namespace Metadata
{
    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
        public int ID { get; set; }
        public string Classname { get; set; }
        public Shift Classshift { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}