// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Metadata.Enums;
using System;
using System.Collections.Generic;

#nullable disable

namespace Metadata
{
    public partial class Lesson
    {
        private Teacher teacher;
        private Class @class;

        public Lesson(DayOfWeek dayOfWeek)
        {
            Lessondate = dayOfWeek;
        }

        public Lesson()
        {

        }

        public Lesson(Teacher teacher, Class @class)
        {
            this.teacher = teacher;
            this.@class = @class;
        }

        public int ID { get; set; }
        public DayOfWeek Lessondate { get; set; }
        public int SubjectTeacherID { get; set; }
        public virtual SubjectTeachers SubjectTeachers { get; set; }
        public int ClassID { get; set; }
        public virtual Class Class { get; set; }
        public Shift Shift { get; set; }
        public LessonOrder Order { get; set; }
        public virtual LessonsStudent PresenceList{ get; set; }
    }
}