// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Metadata
{
    public partial class Subject
    {
        public Subject()
        {
            this.Teachers = new HashSet<SubjectTeachers>();
        }
        public int ID { get; set; }
        public string Subjectname { get; set; }
        public bool Active { get; set; }
        public virtual ICollection<SubjectTeachers> Teachers { get; set; }
    }
}